name: osrs-dmg-sim-deploy

env:
  VENV_FOLDER: ./.venv

on:
  workflow_run:
    workflows: [osrs-dmg-sim-test]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      
      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: $VENV_FOLDER/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}

      - name: Create venv
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv $VENV_FOLDER
          . $VENV_FOLDER/bin/activate
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        run: |
          aws configure set region eu-central-1 --profile default
          aws configure set output json --profile default
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile default
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default

      - name: Zappa deploy to AWS
        run: |
          . $VENV_FOLDER/bin/activate
          zappa update production
