name: web-app-deploy

on:
  workflow_run:
    workflows: [web-app-test]
    types: [completed]
    #TODO branches: [main]

jobs:
  deploy:
    name: Deploy to GitHub pages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ./frontend/osrs-damage-sim

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Deploy
        run: ng deploy --base-href=https://maurits825.github.io/osrs-damage-sim/
