name: web-app-test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/osrs-damage-sim

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run linters
        run: npm run lint
