name: web-app-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/osrs-damage-sim

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run linters
        run: npm run lint
