name: web-app-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/osrs-damage-sim

    steps:
      - name: Check out
        uses: actions/checkout@v3
        
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: ./frontend/osrs-damage-sim/node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nodemodules-

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install --legacy-peer-deps
        
      - name: Debug
        run: ls
        
      - name: Debug3
        run: ls node_modules
        
      - name: Lint
        run: npm run lint
